### ISSUE TITLE
Sample scripts not working in python3.9 (AttributeError: module 'base64' has no attribute 'encodestring')

### ISSUE THREAD

**Issue by snkellner** [NetApp/ontap-rest-python#26]
Hi,
I tried to use the sample scripts on a new system that was updated with the actual python version 3.9. Here the scripts get the following error.
  File "/Users/skellner/OneDrive - NetApp Inc/Repositories/ontap-rest-python/examples/rest_api/create_volume.py", line 153, in <module>
    base64string = base64.encodestring(
AttributeError: module 'base64' has no attribute 'encodestring'

With python 3.8 it still works but gets a warning:
./create_volume.py:153: DeprecationWarning: encodestring() is a deprecated alias since 3.1, use encodebytes()
  base64string = base64.encodestring(

**Comment by mahaganesan11** [comment]
Hi Snkellner,
   We have tested this in **Python 3.6 version** which is compatible as well. 
  Since it's just a warning **with specific version of 3.8 and above**, I'll still try to update the code and will push the latest as early as possible. 
Thanks much for your valuable feedback. Appreciate it.
